// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Ue5Iv-V42M2Fn12SvILDfQWh9VjcivI',
    appId: '1:457570772837:web:d7ce7150433a950927a38c',
    messagingSenderId: '457570772837',
    projectId: 'e-book-iic',
    authDomain: 'e-book-iic.firebaseapp.com',
    storageBucket: 'e-book-iic.appspot.com',
    measurementId: 'G-4LFMHR3RGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDulvVolqQqkMzaLC7vhLtHzxPbWweJLQo',
    appId: '1:457570772837:android:8c245945408fa65827a38c',
    messagingSenderId: '457570772837',
    projectId: 'e-book-iic',
    storageBucket: 'e-book-iic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkwxN3TMG2ZsFXMqJOC4a5bGyLlcC8bz8',
    appId: '1:457570772837:ios:fef651e36201961727a38c',
    messagingSenderId: '457570772837',
    projectId: 'e-book-iic',
    storageBucket: 'e-book-iic.appspot.com',
    iosBundleId: 'com.example.projectEbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkwxN3TMG2ZsFXMqJOC4a5bGyLlcC8bz8',
    appId: '1:457570772837:ios:42ed127ae29f98b027a38c',
    messagingSenderId: '457570772837',
    projectId: 'e-book-iic',
    storageBucket: 'e-book-iic.appspot.com',
    iosBundleId: 'com.example.projectEbook.RunnerTests',
  );
}
